name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.4.2
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - boto3
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cloudpickle=1.3.0
  - configparser=5.0.0
  - cryptography=2.8
  - cycler=0.10.0
  - databricks-cli=0.9.1
  - dbus=1.13.6
  - docker-py=4.2.0
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - expat=2.2.9
  - flask=1.1.2
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - gitdb=4.0.2
  - gitpython=3.1.0
  - glib=2.58.3
  - gorilla=0.3.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gunicorn=20.0.4
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mlflow=1.7.2
  - more-itertools=8.2.0
  - mypy=0.770
  - mypy_extensions=0.4.3
  - ncurses=6.1
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - packaging=20.1
  - pandas=1.0.3
  - pcre=8.44
  - pillow=7.1.1
  - pip=20.0.2
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prometheus_flask_exporter=0.13.0
  - protobuf=3.11.4
  - psutil=5.7.0
  - pthread-stubs=0.4
  - py=1.8.1
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.8
  - pytz=2019.3
  - pyyaml=5.3.1
  - qt=5.12.5
  - querystring_parser=1.2.4
  - readline=8.0
  - requests=2.23.0
  - scikit-learn=0.21
  - scipy=1.4.1
  - setuptools=46.1.3
  - simplejson=3.17.0
  - six=1.14.0
  - smmap=3.0.1
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - sqlparse=0.3.1
  - tabulate=0.8.7
  - tk=8.6.10
  - tornado=6.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wcwidth=0.1.9
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wordcloud=1.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
